spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  task:
    execution:
      pool:
        core-size: 1

server:
  tomcat:
    threads:
      max: 20
file:
  path: C:\Users\ksd56\Desktop\Coding\00_PSA_PortableServiceAdapter\1ComputerMaster\Study\tester\input.txt


